---
- hosts: localhost
  become: true
  connection: local
  vars:
  roles:
  tasks:
    - name: Updating Apk Cache
      apk:
        update_cache: yes

    - name: Installing Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'rsyslog'
        - 'supervisor'

    - name: Installing DNSMasq
      apk:
        name: "dnsmasq"
        state: "present"

    - name: Creating Folders
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - '/etc/supervisor.d'
        - '/etc/dnsmasq.d'
